#
# Project Configuration File
#
# A detailed documentation with the EXAMPLES is located here:
# http://docs.platformio.org/en/latest/projectconf.html
#

# A sign `#` at the beginning of the line indicates a comment
# Comment lines are ignored.

# Simple and base environment
# [env:mybaseenv]
# platform = %INSTALLED_PLATFORM_NAME_HERE%
# framework =
# board =
# Automatic targets - enable auto-uploading
# targets = upload
# ESP32 environment (added to allow building for ESP32 boards)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
# Library Dependency Finder mode - helps find libs in lib/ and lib/*/src
lib_ldf_mode = deep
lib_deps =
    madhephaestus/ESP32Servo
